name: macOS Runner (Metal)

on: workflow_dispatch

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: armorcore/Kinc/make --from armorcore -g metal
